// Code generated by mockery v2.9.3. DO NOT EDIT.

package mocks

import (
	cobra "github.com/spf13/cobra"

	mock "github.com/stretchr/testify/mock"
)

// ITimer is an autogenerated mock type for the ITimer type
type ITimer struct {
	mock.Mock
}

// GetDeltaDuration provides a mock function with given fields:
func (_m *ITimer) GetDeltaDuration() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetTotalDuration provides a mock function with given fields:
func (_m *ITimer) GetTotalDuration() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// SetDeltaDuration provides a mock function with given fields: _a0
func (_m *ITimer) SetDeltaDuration(_a0 *cobra.Command) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cobra.Command) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetTotalDuration provides a mock function with given fields: _a0
func (_m *ITimer) SetTotalDuration(_a0 *cobra.Command) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cobra.Command) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUpTimer provides a mock function with given fields: _a0
func (_m *ITimer) SetUpTimer(_a0 *cobra.Command) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cobra.Command) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
