// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	systeminfo "github.com/altnum/sensorapp/system_info"
)

// IWriter is an autogenerated mock type for the IWriter type
type IWriter struct {
	mock.Mock
}

// StartWriting provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *IWriter) StartWriting(_a0 string, _a1 systeminfo.Measurement, _a2 string, _a3 string) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, systeminfo.Measurement, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
