// Code generated by mockery v2.9.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	systeminfo "github.com/altnum/sensorapp/system_info"
)

// SystemSensor is an autogenerated mock type for the SystemSensor type
type SystemSensor struct {
	mock.Mock
}

// GetInstanceId provides a mock function with given fields:
func (_m *SystemSensor) GetInstanceId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StartMeasurement provides a mock function with given fields: _a0
func (_m *SystemSensor) StartMeasurement(_a0 string) (systeminfo.Measurement, error) {
	ret := _m.Called(_a0)

	var r0 systeminfo.Measurement
	if rf, ok := ret.Get(0).(func(string) systeminfo.Measurement); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(systeminfo.Measurement)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
