// Code generated by mockery v2.9.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IMeasurement is an autogenerated mock type for the IMeasurement type
type IMeasurement struct {
	mock.Mock
}

// SetTimeStamp provides a mock function with given fields:
func (_m *IMeasurement) SetTimeStamp() {
	_m.Called()
}
