{
 "title": "Sensor App",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sensors Correlation",
   "type": "table",
   "description": "CPU Temperature and CPU Usage percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.deviceid1", "language": "jsonpath", "type": "number" },
      { "jsonPath": "$.sensorid1", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.deviceid2", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.sensorid2", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.correlation", "language": "jsonata", "name": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "description": "To add for Fahrenheit",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SensorAverage (memoryAvailableBytes)",
   "type": "table",
   "description": "memoryAvailableBytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.deviceid" },
      { "jsonPath": "$.sensorid", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.average", "language": "jsonpath", "name": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "rawSql": "SELECT * from device;" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "rawSql": "SELECT * FROM sensors " }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}