apiVersion: 1

deleteDatasources:

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: false
    orgId: 1
    basicAuth: false
    isDefault: true
    secureJsonData:
      token: mytoken
    jsonData:
      version: Flux
      organization: sensor-org
      defaultBucket: sensors-bucket
      tlsSkipVerify: true
      timeInterval: "1m"
      httpMode: "POST"
  - name: PostgreSQL
    type: postgres
    url: postgresql:5432
    user: postgres
    secureJsonData:
      password: '1234'
    jsonData:
      database: postgres
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
