// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	database_instances "github.com/altnum/sensorapp/databases/database_instances"

	mock "github.com/stretchr/testify/mock"
)

// IDatabaseFactory is an autogenerated mock type for the IDatabaseFactory type
type IDatabaseFactory struct {
	mock.Mock
}

// ConnectDatabases provides a mock function with given fields: _a0, _a1
func (_m *IDatabaseFactory) ConnectDatabases(_a0 context.Context, _a1 []database_instances.IDB) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []database_instances.IDB) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveDatabases provides a mock function with given fields:
func (_m *IDatabaseFactory) RetrieveDatabases() []database_instances.IDB {
	ret := _m.Called()

	var r0 []database_instances.IDB
	if rf, ok := ret.Get(0).(func() []database_instances.IDB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database_instances.IDB)
		}
	}

	return r0
}
